on:
  pull_request:
  push:
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2     # checkout the repo
#      - run: npm ci                   # install packages

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JUnit Tests            # Name of the check run which will be created
          path: reports/*.xml    # Path to test results
          reporter: java-junit        # Format of test results
