name: Junit Tests
on:
  pull_request:
  push:
jobs:
  build-test:
    name: Build & Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2     # checkout the repo
      - run: npm install ci           # install packages
#      - name: Make gradlew executable
      - run: chmod +x ./gradlew
      - run: ./gradlew build


      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JUnit Tests            # Name of the check run which will be created
          path: build/test-results/test/*.xml    # Path to test results
          reporter: java-junit        # Format of test results
